### ISSUE TITLE
How to run from console_scripts / entrypoint?

### ISSUE THREAD

**Issue by joernheissler** [python-trio/asyncclick#12]
Hello!

I'm trying to build an async cli utility which I can install using pip and which creates an entrypoint script.
See https://packaging.python.org/specifications/entry-points/ or https://python-poetry.org/docs/pyproject/#scripts for details about this feature.

How should my code look like?
```python3

import asyncclick as click
@click.command()
async def run():
    print("foo")
```

```toml
[tool.poetry.scripts]
foobar = "foobar.cli:run"
```

kind of works. But it's running with `asyncio` instead of `trio`.
I don't see any way to pass `_anyio_backend="trio"` without creating another synchronous function.

**Comment by smurfix** [comment]
That's right. You need to create a (simple) sync function, or you can do this:
```
from functools import partial
run = partial(run, _anyio_backend="trio")
```

**Comment by smurfix** [comment]
That being said, adding a decorator that does this is probably the cleanest solution. I'll do that in the next version.

**Comment by smurfix** [comment]
Fixed in current main, there's now an ``@asyncclick.async_backend`` decorator.
