### ISSUE TITLE
How to run_forever?

### ISSUE THREAD

**Issue by mreschke** [python-trio/asyncclick#15]
Creating a multi-socket listener like in https://stackoverflow.com/questions/62571622/running-multiple-sockets-using-asyncio-in-python

Works if not using asyncclick to fire up my own even loop and run_forever() as in the stackoverflow example.  If I was just running one socket, a socket.serve_forever() works fine, but I need to run multiples and therefore run the main loop forever.  Do you know how I can accomplish this with an asyncclick command line?  Can't just grap the `get_running_loop()` and run_forever as it errors with `This event loop is already running`.

**Comment by smurfix** [comment]
Instead of `run_forever` you can simply do nothing forever: `while True: await anyio.sleep(99999)`. Or await the last task directly instead of feeding it to `asyncio.create_task`.

**Comment by mreschke** [comment]
So you are saying something like this:

Either as a Loop
```python
import anyio
@command()
async def cli():
    server1 = await asyncio.start_server(handle_connection, host='127.0.0.1', port=1234)
    server2 = await asyncio.start_server(handle_connection, host='127.0.0.1', port=1235)
    while True:
        await anyio.sleep(999999)
```

or by awaiting only the last infinite serve
```python
@command()
async def cli():
    server1 = await asyncio.start_server(handle_connection, host='127.0.0.1', port=1234)
    server2 = await asyncio.start_server(handle_connection, host='127.0.0.1', port=1235)
    async with server2:
        await server2.serve_forever()
```

They do both seem to work, both ports are nmap as OPEN.

**Comment by smurfix** [comment]
Umm, well you need to run `serve_forever` on both of these if you want something to actually happen if something connects to them, so more along the lines of
```
async def run(server, port):
    server = await asyncio.start_server(handle_connection, host='127.0.0.1', port=port)
    async with server:
        await server.serve_forever()

@command()
async def cli():
    asyncio.start_task(run(1234))
    asyncio.start_task(run(1235))
    while True:
        await asyncio.sleep(999999)
```

**Comment by smurfix** [comment]
edit: corrected for asyncio syntax. anyio has `spawn(proc, arg)` instead of `start_task(proc(arg))`.
