### ISSUE TITLE
Release new version to PyPi

### ISSUE THREAD

**Issue by septatrix** [python-trio/asyncclick#18]
The current version listed there does not declare the anyio dependency whereas the file currently in the repo does.

**Comment by bnavigator** [comment]
This project is dead?

**Comment by smurfix** [comment]
It's not.

**Comment by smurfix** [comment]
Pushed.

**Comment by bnavigator** [comment]
The PyPI release 8.1.7.1 does not have a corresponding git tag in the source code.

**Comment by smurfix** [comment]
*Sigh* git didn't push it.

It does now.
