### ISSUE TITLE
Dependencies of asyncclick are incomplete

### ISSUE THREAD

**Issue by hf-kklein** [python-trio/asyncclick#26]
I installed asyncclick using
```bash
pip install asyncclick
```

- Python version: 3.11

Then I tried to use it and ran into an error:
> No module named 'anyio'  File "/path/to/where/I/used/asyncclick/src/foo.py", line 12, in <module>     import asyncclick as click ModuleNotFoundError: No module named 'anyio'

**Comment by hf-krechan** [comment]
This issue is the same as https://github.com/python-trio/asyncclick/issues/18

**Comment by drernie** [comment]
Is this project still being maintained? Should I move over to your fork @hf-kklein ?

**Comment by hf-kklein** [comment]
@drernie sorry, I'm not maintaining any fork as of now :D

**Comment by smurfix** [comment]
Sorry, I'm waiting for anyio 4.0 before working on this. Shouldn't take much longer.

**Comment by drernie** [comment]
Totally fair! I will go back to trying to bribe him :-)
