### ISSUE TITLE
How to add instrumentation?

### ISSUE THREAD

**Issue by sztomi** [python-trio/asyncclick#3]
In the trio tutorial, there's an example that provides an example of adding instrumentation to the code: https://trio.readthedocs.io/en/latest/tutorial.html#tutorial-instrument-example

trio-click hides the `run` call; is there a way to pass `instruments` to it anyway?

**Comment by smurfix** [comment]
There's now a way to set the backend. Backend-specific options should be easy to add on top of that.

**Comment by smurfix** [comment]
You can set up your event loop as usual, then call `await cli.main()` (or however you named your command line handler).
