### ISSUE TITLE
Revert some of commit 9676da78a

### ISSUE THREAD

**Issue by Ninpo** [python-trio/asyncclick#4]
I'm looking at implementing trio-click into a real world application.  Is it safe to either revert this commit and put back the required items (incorrect import, lines 438-441 etc)

https://github.com/python-trio/trio-click/commit/9676da78a3db5c55f2ad49fda25f58d76c78878a

or would it be preferred to just provide a PR removing the print/gc() parts?

**Comment by smurfix** [comment]
done for some time
