### ISSUE TITLE
Multiple trio-click/asyncclick repositories

### ISSUE THREAD

**Issue by makkus** [python-trio/asyncclick#5]
Heya. It's a bit confusing that there are 3 (that I know of) asyncclick/trio-click repositories.

It looks like this is the 'official' one, right? I think the fact that this one is 'forked from smurfix/trio-click' causes a few issues. I tried to create a pull request here, but I always get redirected to the 'smurfix' one. 

Initially I created the pull request on https://github.com/click-contrib/asyncclick, before there was a mention to go there.

Also, quick question: does the fact that this is named 'trio-click' mean only 'trio' will be 'supported' in the long run? I use this with asyncio (which works fine for now), but would be good to know if this may change in the long run...

**Comment by ayharano** [comment]
Also related to this issue:

asyncclick' setup.py points to http://github.com/python-trio/asyncclick

https://github.com/python-trio/trio-click/blob/bac4f5404749772f315b90ea38fe02de81681835/setup.py#L25


This is important because [PyPI's asyncclick entry](https://pypi.org/project/asyncclick/) points its homepage to an invalid URL in [trio-click organization](https://github.com/python-trio).

**Comment by graingert** [comment]
did you know, you can [contact github support](https://support.github.com/contact) to swap the direction of your forks, so that @smurfix / trio-click becomes a fork of python-trio/trio-click ?

**Comment by njsmith** [comment]
tbh I'm not sure what's supposed to be happening here either. @smurfix can you sort us out?

**Comment by graingert** [comment]
I think this needs an organization admin to rename the repository, @njsmith

**Comment by graingert** [comment]
I think the desired outcome is:

https://github.com/smurfix/trio-click/ -> 302 -> https://github.com/python-trio/asyncclick
https://github.com/trio-click/trio-click/ -> 302 -> https://github.com/python-trio/asyncclick

@smurfix can you confirm?

**Comment by smurfix** [comment]
Yeah, that would be helpful.
I've been neglecting asyncclick a bit but I'm working on merging the latest click release (plus anyio 2.0 compatibility).

**Comment by njsmith** [comment]
@graingert I don't see a `trio-click` org?

**Comment by graingert** [comment]
yeah sorry, that was a copy/paste error, here's the correction:

I think the desired outcome is:

https://github.com/smurfix/trio-click/ -> 302 -> https://github.com/python-trio/asyncclick
https://github.com/python-trio/trio-click/ -> 302 -> https://github.com/python-trio/asyncclick

@smurfix can you confirm?

**Comment by smurfix** [comment]
Yes, sure. I missed the earlier `trio-click` thing.

**Comment by njsmith** [comment]
Hmm, ok, so in that case possibly the simplest way to accomplish that combination of redirects would be to:

1. delete this repo
2. transfer `smurfix/trio-click` to the python-trio org, so it becomes `python-trio/trio-click`
3. rename `python-trio/trio-click` → `python-trio/asyncclick`

Does that seem like a good plan? Would we be losing anything important if we deleted this repo in favor of the repo that's currently called `smurfix/trio-click`?

**Comment by graingert** [comment]
You could rename this repo, or move it to another org. Also I think GitHub support can do it all in one go with permission from the owners

**Comment by smurfix** [comment]
I have just asked github support about how to redirect `smurfix/asyncclick` to `python-trio/`. Though deleting this one and moving my personal one over here would work for me.

**Comment by smurfix** [comment]
Should be all done now
