### ISSUE TITLE
Is asyncclick can't use in windows?

### ISSUE THREAD

**Issue by ShirleyChau** [python-trio/asyncclick#8]
When I used it in windows,I got an error that:    `_wrap_std_stream' from 'asyncclick._winconsole`
But when I used it in wsl,it was available.
All error info :
`
(aerichtest-Io3kg-ro-py3.8) C:\Users\surface\PycharmProjects\aerichTest>aerich init -h Traceback (most recent call last): File "C:\Users\surface\AppData\Local\pypoetry\Cache\virtualenvs\aerichtest-Io3kg-ro- py3.8\Scripts\aerich-script.py", line 11, in <module> load_entry_point('aerich', 'console_scripts', 'aerich')() File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro- py3.8\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro- py3.8\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point return ep.load() File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro- py3.8\lib\site-packages\pkg_resources\__init__.py", line 2462, in load return self.resolve() File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro- py3.8\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro- py3.8\src\aerich\aerich\cli.py", line 8, in <module> import asyncclick as click File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro- py3.8\lib\site-packages\asyncclick\__init__.py", line 7, in <module> from .core import Argument File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-py3.8\lib\site-packages\asyncclick\core.py", line 18, in <module> from ._compat import isidentifier File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-py3.8\lib\site-packages\asyncclick\_compat.py", line 540, in <module> from ._winconsole import _get_windows_console_stream, _wrap_std_stream ImportError: cannot import name '_wrap_std_stream' from 'asyncclick._winconsole' (c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-py3.8\lib\site-packa ges\asyncclick\_winconsole.py)
`
 

### Environment

* Python version:3.8
* Click version:7.1.2.1

**Comment by gimebreak** [comment]
I also have the same issue

**Comment by ShirleyChau** [comment]
Now I use the other method:
I create a Decorator
`

def open_db(func):
    async def open_db_inner(*args, **kwargs):
        result = await func(*args, **kwargs)
        await Tortoise.close_connections()
        return result
    @functools.wraps(func)
    def close_db_inner2(*args, **kwargs):
        return asyncio.run(close_db_inner(*args, **kwargs))
    return close_db_inner2

`

**Comment by auphofBSF** [comment]
I am encountering same issue: (Windows) Please reopen this issue !

Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)] on win32

```
import anyio
import asyncclick as click

@click.command()
@click.option("--count", default=1, help="Number of greetings.")
@click.option("--name", prompt="Your name", help="The person to greet.")
async def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        if x: await anyio.sleep(0.1)
        click.echo(f"Hello, {name}!")

if __name__ == '__main__':
    hello(_anyio_backend="asyncio")  # or asyncio, or curio
```

```
Traceback (most recent call last):
  File ".\Example_asyncclick.py", line 2, in <module>
    import asyncclick as click
  File "C:\Users\<USER>\Anaconda3\envs\<ENV>\lib\site-packages\asyncclick\__init__.py", line 7, in <module>
    from .core import Argument
  File "C:\Users\<USER>\Anaconda3\envs\<ENV>\\lib\site-packages\asyncclick\core.py", line 18, in <module>
    from ._compat import isidentifier
  File "C:\Users\<USER>\Anaconda3\envs\<ENV>\\lib\site-packages\asyncclick\_compat.py", line 540, in <module>
    from ._winconsole import _get_windows_console_stream, _wrap_std_stream
ImportError: cannot import name '_wrap_std_stream' from 'asyncclick._winconsole' (C:\Users\<USER>\Anaconda3\envs\<ENV>\\lib\site-packages\asyncclick\_winconsole.py)
```
When I down grade to `pip install asyncclick==7.0.9` (as mentioned in https://github.com/python-kasa/python-kasa/issues/106) Then all works OK !

**Comment by smurfix** [comment]
Does non-async-click work?

**Comment by auphofBSF** [comment]
Yes

**Comment by smurfix** [comment]
Owch. Will look into it.

**Comment by smurfix** [comment]
Unused import. Please check whether the current master fixes this.

**Comment by auphofBSF** [comment]
SUCCESS,  thank you
uninstalled 7.09, cloned master d18b28e and did `pip install -e .`   and all working well 🙏

**Comment by smurfix** [comment]
Great. Uploaded 7.1.2.2 to pypi.
